"use strict";

function v18Portrait(name) {
  return {
    image: `assets/v18/master/${name}-4k.webp`,
    medium: `assets/v18/${name}-1440.webp`,
    small: `assets/v18/${name}-720.webp`,
    width: 3072,
    mediumWidth: 1440,
    smallWidth: 720,
  };
}

function v18Scene(name) {
  return {
    image: `assets/v18/master/${name}-4k.webp`,
    medium: `assets/v18/${name}-1440.webp`,
    small: `assets/v18/${name}-720.webp`,
    thumb: `assets/v18/${name}-480.webp`,
    width: 3840,
    mediumWidth: 1440,
    smallWidth: 720,
  };
}

function v19Portrait(name) {
  return {
    image: `assets/v19/master/${name}-4k.webp`,
    medium: `assets/v19/${name}-1440.webp`,
    small: `assets/v19/${name}-720.webp`,
    width: 3072,
    mediumWidth: 1440,
    smallWidth: 720,
  };
}

function v19Scene(name) {
  return {
    image: `assets/v19/master/${name}-4k.webp`,
    medium: `assets/v19/${name}-1440.webp`,
    small: `assets/v19/${name}-720.webp`,
    thumb: `assets/v19/${name}-480.webp`,
    width: 3840,
    mediumWidth: 1440,
    smallWidth: 720,
  };
}

const CONTENT = {
  cinematicScenes: [
    {
      id: "door",
      sectionId: "cinematic-door",
      label: "第一幕 · 房门",
      shortLine: "她听见了，却还在确认是不是你。",
      detailsLabel: "展开门口原稿",
      frameKind: "portrait",
      frames: [
        {
          id: "door-peek",
          at: 0,
          label: "安静偷看",
          ...v19Portrait("door-peek"),
          alt: "纱雾从半掩的卧室门后安静偷看",
        },
        {
          id: "door-listen",
          at: 0.28,
          label: "侧耳确认",
          ...v19Portrait("door-listen"),
          alt: "纱雾贴近门边侧耳确认来访者",
        },
        {
          id: "door-startled",
          at: 0.58,
          label: "吓了一跳",
          ...v19Portrait("door-startled"),
          alt: "敲门声响起时纱雾睁大蓝眼睛轻轻受惊",
        },
        {
          id: "door-open-smile",
          at: 0.86,
          label: "认出你了",
          ...v19Portrait("door-open-smile"),
          alt: "纱雾打开房门后脸红着露出安心微笑",
        },
      ],
      camera: {
        desktop: [
          { x: 3, y: -2, scale: 1.11 },
          { x: -1, y: -3, scale: 1.16 },
          { x: -2, y: -1, scale: 1.1 },
          { x: 1, y: 0, scale: 1.04 },
        ],
        mobile: [
          { x: 4, y: -1, scale: 1.16 },
          { x: 1, y: -2, scale: 1.19 },
          { x: -2, y: 0, scale: 1.13 },
          { x: 0, y: 0, scale: 1.07 },
        ],
      },
      inspectFrameId: "door-peek",
      transition: "door-edge",
      characterVoiceId: "door-closer",
      hotspots: [
        {
          id: "door-panel",
          label: "轻敲木门",
          desktopPosition: { x: 20, y: 42 },
          mobilePosition: { x: 18, y: 45 },
          reactionFrame: "door-listen",
          voiceId: "door-knock-wait",
          foleyId: "door-knock-soft",
        },
        {
          id: "door-handle",
          label: "轻轻转动门把",
          desktopPosition: { x: 27, y: 71 },
          mobilePosition: { x: 27, y: 71 },
          reactionFrame: "door-startled",
          voiceId: "door-handle",
          foleyId: "door-handle-turn",
        },
        {
          id: "door-gap",
          label: "看看亮起的门缝",
          desktopPosition: { x: 35, y: 27 },
          mobilePosition: { x: 35, y: 27 },
          reactionFrame: "door-open-smile",
          voiceId: "door-startled",
          foleyId: "door-open-gentle",
        },
      ],
    },
    {
      id: "room",
      sectionId: "cinematic-room",
      label: "第二幕 · 房间",
      shortLine: "笔尖没有停，旁边的椅子却悄悄空出来。",
      detailsLabel: "展开房间原稿",
      frameKind: "scene",
      frames: [
        {
          id: "room-drawing",
          at: 0,
          label: "继续画画",
          ...v19Scene("room-drawing"),
          alt: "纱雾趴在数位板前认真画画",
        },
        {
          id: "room-stops-pen",
          at: 0.28,
          label: "笔尖停住",
          ...v19Scene("room-stops-pen"),
          alt: "纱雾察觉到你以后暂时停住数位笔",
        },
        {
          id: "room-glances-over",
          at: 0.58,
          label: "悄悄回望",
          ...v19Scene("room-glances-over"),
          alt: "纱雾从银白长发间害羞地回头看你",
        },
        {
          id: "room-invites-seat",
          at: 0.86,
          label: "空出椅子",
          ...v19Scene("room-invites-seat"),
          alt: "纱雾把旁边的椅子轻轻推出来邀请你坐下",
        },
      ],
      camera: {
        desktop: [
          { x: 0, y: 2, scale: 1.03 },
          { x: -3, y: 2, scale: 1.06 },
          { x: 3, y: -1, scale: 1.08 },
          { x: -1, y: 1, scale: 1.03 },
        ],
        mobile: [
          { x: -4, y: 2, scale: 1.08 },
          { x: -5, y: 3, scale: 1.1 },
          { x: 4, y: -1, scale: 1.12 },
          { x: 1, y: 1, scale: 1.08 },
        ],
      },
      inspectFrameId: "room-invites-seat",
      transition: "tablet-edge",
      characterVoiceId: "room-stay",
      hotspots: [
        {
          id: "room-pen",
          label: "听数位笔划过板面",
          desktopPosition: { x: 38, y: 65 },
          mobilePosition: { x: 38, y: 65 },
          reactionFrame: "room-stops-pen",
          voiceId: "room-pen-tip",
          foleyId: "room-stylus-glide",
        },
        {
          id: "room-chair",
          label: "把椅子轻轻挪近",
          desktopPosition: { x: 78, y: 55 },
          mobilePosition: { x: 78, y: 55 },
          reactionFrame: "room-invites-seat",
          voiceId: "room-chair",
          foleyId: "room-chair-slide",
        },
        {
          id: "room-curtain",
          label: "替她拉上一点窗帘",
          desktopPosition: { x: 76, y: 22 },
          mobilePosition: { x: 76, y: 22 },
          reactionFrame: "room-glances-over",
          voiceId: "room-curtain",
          foleyId: "room-curtain-slide",
        },
      ],
    },
    {
      id: "secrets",
      sectionId: "cinematic-secrets",
      label: "第三幕 · 桌面秘密",
      shortLine: "每件被收好的东西，都比她更会说实话。",
      detailsLabel: "展开秘密原稿",
      frameKind: "scene",
      frames: [
        {
          id: "secrets-caught",
          at: 0,
          label: "被她发现",
          ...v19Scene("secrets-caught"),
          alt: "纱雾发现你在看桌上的耳机和稿纸",
        },
        {
          id: "secrets-protects-draft",
          at: 0.46,
          label: "护住草稿",
          ...v19Scene("secrets-protects-draft"),
          alt: "纱雾慌忙用袖口护住还没完成的草稿",
        },
        {
          id: "secrets-opens-drawer",
          at: 0.82,
          label: "一起开抽屉",
          ...v19Scene("secrets-opens-drawer"),
          alt: "纱雾红着脸陪你打开木桌抽屉",
        },
      ],
      camera: {
        desktop: [
          { x: -2, y: 2, scale: 1.04 },
          { x: 3, y: 4, scale: 1.08 },
          { x: -3, y: 3, scale: 1.07 },
        ],
        mobile: [
          { x: -4, y: 3, scale: 1.08 },
          { x: 5, y: 4, scale: 1.12 },
          { x: -5, y: 4, scale: 1.1 },
        ],
      },
      inspectFrameId: "secrets-opens-drawer",
      transition: "drawer-edge",
      characterVoiceId: "secrets-nothing-weird",
      hotspots: [
        {
          id: "secrets-headphones",
          label: "把耳机放回原来的方向",
          desktopPosition: { x: 8, y: 34 },
          mobilePosition: { x: 8, y: 34 },
          reactionFrame: "secrets-caught",
          voiceId: "secrets-headphones",
          foleyId: "secrets-headphones-set",
        },
        {
          id: "secrets-draft",
          label: "掀起草稿的一角",
          desktopPosition: { x: 24, y: 82 },
          mobilePosition: { x: 24, y: 82 },
          reactionFrame: "secrets-protects-draft",
          voiceId: "secrets-draft",
          foleyId: "secrets-paper-lift",
        },
        {
          id: "secrets-drawer",
          label: "碰一下抽屉锁扣",
          desktopPosition: { x: 87, y: 91 },
          mobilePosition: { x: 87, y: 91 },
          reactionFrame: "secrets-opens-drawer",
          voiceId: "secrets-drawer",
          foleyId: "secrets-drawer-latch",
        },
      ],
    },
    {
      id: "wardrobe",
      sectionId: "cinematic-wardrobe",
      label: "第四幕 · 衣橱",
      shortLine: "她说只是试一下，却一直等你点头。",
      detailsLabel: "展开衣橱原稿",
      frameKind: "portrait",
      frames: [
        {
          id: "wardrobe-hides-sleeves",
          at: 0,
          label: "袖口藏手",
          ...v19Portrait("wardrobe-hides-sleeves"),
          alt: "纱雾害羞地把双手藏进长长的袖口",
        },
        {
          id: "wardrobe-holds-two",
          at: 0.28,
          label: "举起两套",
          ...v19Portrait("wardrobe-holds-two"),
          alt: "纱雾举起轮廓不同的两套衣服等你挑选",
        },
        {
          id: "wardrobe-adjusts-bow",
          at: 0.58,
          label: "整理蝴蝶结",
          ...v19Portrait("wardrobe-adjusts-bow"),
          alt: "纱雾低头认真调整胸前的小蝴蝶结",
        },
        {
          id: "wardrobe-chosen-shy",
          at: 0.86,
          label: "选好以后",
          ...v19Portrait("wardrobe-chosen-shy"),
          alt: "纱雾仍穿粉色家居服，抱着选中的薄荷猫耳外套害羞等你回应",
        },
      ],
      camera: {
        desktop: [
          { x: 0, y: 6, scale: 1.01 },
          { x: 0, y: 6, scale: 1.02 },
          { x: 0, y: 7, scale: 1.03 },
          { x: 0, y: 6, scale: 1.02 },
        ],
        mobile: [
          { x: 0, y: 7, scale: 1.03 },
          { x: 0, y: 7, scale: 1.04 },
          { x: 0, y: 8, scale: 1.05 },
          { x: 0, y: 7, scale: 1.04 },
        ],
      },
      inspectFrameId: "wardrobe-holds-two",
      transition: "fabric-edge",
      characterVoiceId: "wardrobe-choice-wait",
      hotspots: [
        {
          id: "wardrobe-hanger",
          label: "轻轻滑动衣架",
          desktopPosition: { x: 27, y: 29 },
          mobilePosition: { x: 27, y: 29 },
          reactionFrame: "wardrobe-holds-two",
          voiceId: "wardrobe-two-outfits",
          foleyId: "wardrobe-hanger-slide",
        },
        {
          id: "wardrobe-sleeve",
          label: "摸摸藏住手的袖口",
          desktopPosition: { x: 22, y: 57 },
          mobilePosition: { x: 22, y: 57 },
          reactionFrame: "wardrobe-hides-sleeves",
          voiceId: "wardrobe-sleeves",
          foleyId: "wardrobe-sleeve-rustle",
        },
        {
          id: "wardrobe-ribbon",
          label: "帮她看蝴蝶结有没有歪",
          desktopPosition: { x: 69, y: 44 },
          mobilePosition: { x: 69, y: 44 },
          reactionFrame: "wardrobe-adjusts-bow",
          voiceId: "wardrobe-ribbon",
          foleyId: "wardrobe-ribbon-rustle",
        },
      ],
    },
    {
      id: "gallery",
      sectionId: "cinematic-gallery",
      label: "第五幕 · 画册",
      shortLine: "画册越往后，她藏起来的速度越慢。",
      detailsLabel: "展开画册原稿",
      frameKind: "scene",
      frames: [
        {
          id: "gallery-hides-book",
          at: 0,
          label: "藏起画册",
          ...v19Scene("gallery-hides-book"),
          alt: "纱雾把大画册挡在脸前只露出一点银白长发",
        },
        {
          id: "gallery-peeks-over",
          at: 0.46,
          label: "从书后偷看",
          ...v19Scene("gallery-peeks-over"),
          alt: "纱雾从画册上方露出蓝眼睛观察你的反应",
        },
        {
          id: "gallery-pushes-book",
          at: 0.82,
          label: "推近最后一页",
          ...v19Scene("gallery-pushes-book"),
          alt: "纱雾红着脸把打开的画册轻轻推到你面前",
        },
      ],
      camera: {
        desktop: [
          { x: 1, y: 1, scale: 1.04 },
          { x: 0, y: -2, scale: 1.08 },
          { x: 0, y: 3, scale: 1.07 },
        ],
        mobile: [
          { x: 0, y: 1, scale: 1.08 },
          { x: 0, y: -3, scale: 1.12 },
          { x: 0, y: 4, scale: 1.1 },
        ],
      },
      inspectFrameId: "gallery-pushes-book",
      transition: "paper-edge",
      characterVoiceId: "gallery-praise",
      hotspots: [
        {
          id: "gallery-cover",
          label: "替她托住画册封面",
          desktopPosition: { x: 34, y: 68 },
          mobilePosition: { x: 34, y: 68 },
          reactionFrame: "gallery-hides-book",
          voiceId: "gallery-first-page",
          foleyId: "gallery-book-open",
        },
        {
          id: "gallery-page",
          label: "慢慢翻过一页",
          desktopPosition: { x: 57, y: 55 },
          mobilePosition: { x: 57, y: 55 },
          reactionFrame: "gallery-peeks-over",
          voiceId: "gallery-turn-slow",
          foleyId: "gallery-page-turn",
        },
        {
          id: "gallery-picture",
          label: "把画纸轻轻滑近",
          desktopPosition: { x: 55, y: 74 },
          mobilePosition: { x: 55, y: 74 },
          reactionFrame: "gallery-pushes-book",
          voiceId: "gallery-close-look",
          foleyId: "gallery-photo-slide",
        },
      ],
    },
    {
      id: "drawing",
      sectionId: "cinematic-drawing",
      label: "第六幕 · 一起画",
      shortLine: "这次，她没有把旁边的位置收回去。",
      detailsLabel: "展开共同创作原稿",
      frameKind: "scene",
      frames: [
        {
          id: "drawing-focus",
          at: 0,
          label: "认真收线",
          ...v19Scene("drawing-focus"),
          alt: "纱雾低头专心画下最后几条线",
        },
        {
          id: "drawing-blink",
          at: 0.2,
          label: "眨一下眼",
          ...v19Scene("drawing-blink"),
          alt: "画到一半的纱雾轻轻眨眼休息",
        },
        {
          id: "drawing-covers-page",
          at: 0.42,
          label: "慌忙遮画",
          ...v19Scene("drawing-covers-page"),
          alt: "发现你偷看后纱雾红着脸用稿纸遮住画面",
        },
        {
          id: "drawing-shy-pause",
          at: 0.66,
          label: "害羞停笔",
          ...v19Scene("drawing-shy-pause"),
          alt: "纱雾握着数位笔害羞地停下来确认你还在",
        },
        {
          id: "drawing-reveal",
          at: 0.86,
          label: "递出完成稿",
          ...v19Scene("drawing-reveal"),
          alt: "纱雾把刚完成的画推到你面前等候感想",
        },
      ],
      camera: {
        desktop: [
          { x: -2, y: 3, scale: 1.05 },
          { x: 1, y: -1, scale: 1.07 },
          { x: 3, y: 2, scale: 1.07 },
          { x: 1, y: -1, scale: 1.06 },
          { x: 0, y: 2, scale: 1.04 },
        ],
        mobile: [
          { x: -4, y: 4, scale: 1.09 },
          { x: 3, y: -2, scale: 1.1 },
          { x: 4, y: 3, scale: 1.1 },
          { x: 2, y: -1, scale: 1.09 },
          { x: 0, y: 3, scale: 1.07 },
        ],
      },
      inspectFrameId: "drawing-covers-page",
      transition: "drawing-paper-edge",
      characterVoiceId: "drawing-you-are-there",
      hotspots: [
        {
          id: "drawing-pen",
          label: "听她再画一条短线",
          desktopPosition: { x: 43, y: 58 },
          mobilePosition: { x: 43, y: 58 },
          reactionFrame: "drawing-focus",
          voiceId: "drawing-one-line",
          foleyId: "drawing-stylus-line",
        },
        {
          id: "drawing-cover",
          label: "轻碰遮住画面的稿纸",
          desktopPosition: { x: 58, y: 68 },
          mobilePosition: { x: 58, y: 68 },
          reactionFrame: "drawing-covers-page",
          voiceId: "drawing-peek-again",
          foleyId: "drawing-paper-cover",
        },
        {
          id: "drawing-sheet",
          label: "接住推近的完成稿",
          desktopPosition: { x: 69, y: 76 },
          mobilePosition: { x: 69, y: 76 },
          reactionFrame: "drawing-reveal",
          voiceId: "drawing-first-view",
          foleyId: "drawing-sheet-push",
        },
      ],
    },
    {
      id: "goodnight",
      sectionId: "cinematic-goodnight",
      label: "第七幕 · 晚安",
      shortLine: "门会合上，但她把明天留了一条缝。",
      detailsLabel: "展开晚安原稿",
      frameKind: "scene",
      frames: [
        {
          id: "goodnight-hug",
          at: 0,
          label: "抱紧玩偶",
          ...v19Scene("goodnight-hug"),
          alt: "纱雾在夜晚床边蜷坐着抱紧猫咪玩偶",
        },
        {
          id: "goodnight-yawn",
          at: 0.46,
          label: "困得打呵欠",
          ...v19Scene("goodnight-yawn"),
          alt: "纱雾抱着猫咪玩偶困倦地打了一个小呵欠",
        },
        {
          id: "goodnight-wave",
          at: 0.82,
          label: "门缝里挥手",
          ...v19Scene("goodnight-wave"),
          alt: "月光下纱雾从将要合上的房门边轻轻挥手",
        },
      ],
      camera: {
        desktop: [
          { x: 2, y: 2, scale: 1.04 },
          { x: 0, y: 2, scale: 1.07 },
          { x: -2, y: 1, scale: 1.04 },
        ],
        mobile: [
          { x: 4, y: 3, scale: 1.08 },
          { x: 0, y: 3, scale: 1.1 },
          { x: -3, y: 2, scale: 1.08 },
        ],
      },
      inspectFrameId: "goodnight-wave",
      transition: "night-window-edge",
      characterVoiceId: "goodnight-sleepy",
      hotspots: [
        {
          id: "goodnight-plush",
          label: "轻轻按一下猫咪玩偶",
          desktopPosition: { x: 54, y: 48 },
          mobilePosition: { x: 54, y: 48 },
          reactionFrame: "goodnight-hug",
          voiceId: "goodnight-plush",
          foleyId: "goodnight-plush-squeeze",
        },
        {
          id: "goodnight-book",
          label: "替她合上怀里的书",
          desktopPosition: { x: 52, y: 63 },
          mobilePosition: { x: 52, y: 63 },
          reactionFrame: "goodnight-yawn",
          voiceId: "goodnight-book",
          foleyId: "goodnight-book-close",
        },
        {
          id: "goodnight-door",
          label: "把房门轻轻合上",
          desktopPosition: { x: 34, y: 75 },
          mobilePosition: { x: 34, y: 75 },
          reactionFrame: "goodnight-wave",
          voiceId: "goodnight-knock-next",
          foleyId: "goodnight-latch",
        },
      ],
    },
  ],
  cinematicVoices: {
    "door-knock-wait": {
      id: "door-knock-wait",
      scene: "房门",
      label: "听见轻敲",
      japanese: "……ちゃんとノックしてくれたんだ。じゃあ、少しだけ待って。",
      chinese: "……你有好好敲门。那就稍微等一下。",
      file: "assets/audio/v19/voice/door-knock-wait.mp3",
      expression: "shy",
      reaction: "听见了……再等我一下。",
      frame: "door-listen",
    },
    "door-startled": {
      id: "door-startled",
      scene: "房门",
      label: "只是一点受惊",
      japanese: "び、びっくりしただけ。怖がってなんかないから。",
      chinese: "只、只是吓了一跳。我才没有害怕。",
      file: "assets/audio/v19/voice/door-startled.mp3",
      expression: "startled",
      reaction: "只、只是吓了一小跳。",
      frame: "door-startled",
    },
    "door-handle": {
      id: "door-handle",
      scene: "房门",
      label: "准备开门",
      japanese: "ドアノブ、そんなに見ないで。今、開けるから。",
      chinese: "别一直盯着门把手。我现在就开。",
      file: "assets/audio/v19/voice/door-handle.mp3",
      expression: "startled",
      reaction: "别盯着门把手啦……马上就开。",
      frame: "door-startled",
    },
    "door-closer": {
      id: "door-closer",
      scene: "房门",
      label: "允许靠近",
      japanese: "今日は……いつもより、ちょっとだけ近くてもいいよ。",
      chinese: "今天……可以比平时再靠近一点点。",
      file: "assets/audio/v19/voice/door-closer.mp3",
      expression: "shy",
      reaction: "只可以……比平时近一点点。",
      frame: "door-open-smile",
    },
    "room-chair": {
      id: "room-chair",
      scene: "房间",
      label: "空出的椅子",
      japanese: "そこ、椅子を少しだけ空けておいたの。",
      chinese: "那里……我稍微把椅子空出来了。",
      file: "assets/audio/v19/voice/room-chair.mp3",
      expression: "shy",
      reaction: "椅子只是刚好空着……坐吧。",
      frame: "room-invites-seat",
    },
    "room-pen-tip": {
      id: "room-pen-tip",
      scene: "房间",
      label: "笔尖规矩",
      japanese: "ペン先を触るなら、線がずれないようにね。",
      chinese: "要碰笔尖的话，可别让线条歪掉。",
      file: "assets/audio/v19/voice/room-pen-tip.mp3",
      expression: "proud",
      reaction: "线条歪掉的话，要陪我重画。",
      frame: "room-stops-pen",
    },
    "room-curtain": {
      id: "room-curtain",
      scene: "房间",
      label: "窗帘光线",
      japanese: "カーテン、少しだけ閉めて。画面が見やすくなるから。",
      chinese: "把窗帘稍微拉上一点，这样屏幕会更清楚。",
      file: "assets/audio/v19/voice/room-curtain.mp3",
      expression: "peek",
      reaction: "再拉上一点点……这样刚好。",
      frame: "room-glances-over",
    },
    "room-stay": {
      id: "room-stay",
      scene: "房间",
      label: "安静坐在身边",
      japanese: "見てるだけなら……静かに隣にいてもいいよ。",
      chinese: "只是看的话……可以安静待在旁边。",
      file: "assets/audio/v19/voice/room-stay.mp3",
      expression: "shy",
      reaction: "不说话也没关系……我知道你在。",
      frame: "room-invites-seat",
    },
    "secrets-draft": {
      id: "secrets-draft",
      scene: "桌面秘密",
      label: "还没完成的草稿",
      japanese: "そ、それは下書き。まだ見せる予定じゃなかったの。",
      chinese: "那、那只是草稿。我本来没打算给你看的。",
      file: "assets/audio/v19/voice/secrets-draft.mp3",
      expression: "startled",
      reaction: "还没画好……不许看太久。",
      frame: "secrets-protects-draft",
    },
    "secrets-headphones": {
      id: "secrets-headphones",
      scene: "桌面秘密",
      label: "耳机的方向",
      japanese: "ヘッドホンの向き？　いつも同じじゃないと落ち着かないだけ。",
      chinese: "耳机的方向？只是每次不一样我就静不下来。",
      file: "assets/audio/v19/voice/secrets-headphones.mp3",
      expression: "proud",
      reaction: "只是摆整齐以后比较安心。",
      frame: "secrets-caught",
    },
    "secrets-drawer": {
      id: "secrets-drawer",
      scene: "桌面秘密",
      label: "一起看抽屉",
      japanese: "引き出しは……開けるなら、私も一緒に見る。",
      chinese: "抽屉……要打开的话，我也一起看。",
      file: "assets/audio/v19/voice/secrets-drawer.mp3",
      expression: "shy",
      reaction: "要开的话……手不要松开。",
      frame: "secrets-opens-drawer",
    },
    "secrets-nothing-weird": {
      id: "secrets-nothing-weird",
      scene: "桌面秘密",
      label: "没有奇怪东西",
      japanese: "秘密って言っても、変なものは入ってないからね。",
      chinese: "虽说是秘密，里面可没有奇怪的东西。",
      file: "assets/audio/v19/voice/secrets-nothing-weird.mp3",
      expression: "startled",
      reaction: "真、真的没有奇怪的东西。",
      frame: "secrets-caught",
    },
    "wardrobe-sleeves": {
      id: "wardrobe-sleeves",
      scene: "衣橱",
      label: "喜欢长袖",
      japanese: "この袖、長すぎる？　でも、手が隠れるから好き。",
      chinese: "这袖子太长了吗？可我喜欢它能遮住手。",
      file: "assets/audio/v19/voice/wardrobe-sleeves.mp3",
      expression: "shy",
      reaction: "手藏起来的话……就没那么紧张。",
      frame: "wardrobe-hides-sleeves",
    },
    "wardrobe-ribbon": {
      id: "wardrobe-ribbon",
      scene: "衣橱",
      label: "蝴蝶结检查",
      japanese: "リボン、曲がってないかだけ見て。",
      chinese: "只帮我看看蝴蝶结有没有歪。",
      file: "assets/audio/v19/voice/wardrobe-ribbon.mp3",
      expression: "peek",
      reaction: "只看蝴蝶结……别看别的地方。",
      frame: "wardrobe-adjusts-bow",
    },
    "wardrobe-two-outfits": {
      id: "wardrobe-two-outfits",
      scene: "衣橱",
      label: "同时比较两套",
      japanese: "二着いっぺんに比べるの、ちょっと恥ずかしい……。",
      chinese: "一次比较两套，稍微有点害羞……",
      file: "assets/audio/v19/voice/wardrobe-two-outfits.mp3",
      expression: "startled",
      reaction: "两套一起举着……好害羞。",
      frame: "wardrobe-holds-two",
    },
    "wardrobe-choice-wait": {
      id: "wardrobe-choice-wait",
      scene: "衣橱",
      label: "一直等你选择",
      japanese:
        "き、決めたなら早く言って。ずっと待ってるの、もっと恥ずかしいから。",
      chinese: "选、选好了就快点说。一直等着更让人害羞。",
      file: "assets/audio/v19/voice/wardrobe-choice-wait.mp3",
      expression: "startled",
      reaction: "快一点告诉我……我一直在等。",
      frame: "wardrobe-chosen-shy",
    },
    "gallery-first-page": {
      id: "gallery-first-page",
      scene: "画册",
      label: "第一页的线",
      japanese: "最初のページは、まだ線が少し震えてるの。",
      chinese: "第一页的线条还有一点抖。",
      file: "assets/audio/v19/voice/gallery-first-page.mp3",
      expression: "peek",
      reaction: "第一页……不要笑我的线。",
      frame: "gallery-hides-book",
    },
    "gallery-close-look": {
      id: "gallery-close-look",
      scene: "画册",
      label: "靠近看的约定",
      japanese: "その画、近くで見るなら……感想もちゃんと言って。",
      chinese: "要靠近看那张画……也要认真说感想。",
      file: "assets/audio/v19/voice/gallery-close-look.mp3",
      expression: "shy",
      reaction: "看完要认真告诉我感想。",
      frame: "gallery-peeks-over",
    },
    "gallery-turn-slow": {
      id: "gallery-turn-slow",
      scene: "画册",
      label: "慢慢翻页",
      japanese: "ページ、ゆっくりめくって。角が折れたら困るから。",
      chinese: "慢慢翻页。折到书角我会很困扰。",
      file: "assets/audio/v19/voice/gallery-turn-slow.mp3",
      expression: "proud",
      reaction: "书角不可以折到。",
      frame: "gallery-peeks-over",
    },
    "gallery-praise": {
      id: "gallery-praise",
      scene: "画册",
      label: "可以稍微夸奖",
      japanese: "最後まで見たの？　……じゃあ、少しくらい褒めてもいいよ。",
      chinese: "看到最后了吗？……那稍微夸一下也可以。",
      file: "assets/audio/v19/voice/gallery-praise.mp3",
      expression: "proud",
      reaction: "只允许……稍微夸一下。",
      frame: "gallery-pushes-book",
    },
    "drawing-one-line": {
      id: "drawing-one-line",
      scene: "一起画",
      label: "再画一条线",
      japanese: "今いいところだから、あと一本だけ線を引かせて。",
      chinese: "正画到关键地方，让我再画一条线。",
      file: "assets/audio/v19/voice/drawing-one-line.mp3",
      expression: "proud",
      reaction: "就最后一条线……这次是真的。",
      frame: "drawing-focus",
    },
    "drawing-peek-again": {
      id: "drawing-peek-again",
      scene: "一起画",
      label: "又被偷看",
      japanese: "また覗いた。……そんなに気になるの？",
      chinese: "又偷看。……就这么在意吗？",
      file: "assets/audio/v19/voice/drawing-peek-again.mp3",
      expression: "startled",
      reaction: "又偷看……有那么在意吗？",
      frame: "drawing-covers-page",
    },
    "drawing-you-are-there": {
      id: "drawing-you-are-there",
      scene: "一起画",
      label: "知道你还在",
      japanese: "何も言わなくても、そこにいるのは分かってる。",
      chinese: "就算什么都不说，我也知道你在那里。",
      file: "assets/audio/v19/voice/drawing-you-are-there.mp3",
      expression: "shy",
      reaction: "不用说话……我知道你在。",
      frame: "drawing-shy-pause",
    },
    "drawing-first-view": {
      id: "drawing-first-view",
      scene: "一起画",
      label: "第一个给你看",
      japanese: "できた。最初に見せるのは……今日は、あなたでいい。",
      chinese: "画好了。今天第一个给你看的人……可以是你。",
      file: "assets/audio/v19/voice/drawing-first-view.mp3",
      expression: "proud",
      reaction: "今天……先给你看。",
      frame: "drawing-reveal",
    },
    "goodnight-sleepy": {
      id: "goodnight-sleepy",
      scene: "晚安",
      label: "眼睛要合上了",
      japanese: "もう少し起きていたいけど、目が勝手に閉じそう……。",
      chinese: "还想再醒一会儿，可眼睛好像要自己闭上了……",
      file: "assets/audio/v19/voice/goodnight-sleepy.mp3",
      expression: "shy",
      reaction: "眼睛好像……自己要合上了。",
      frame: "goodnight-yawn",
    },
    "goodnight-plush": {
      id: "goodnight-plush",
      scene: "晚安",
      label: "不能少的玩偶",
      japanese: "ぬいぐるみ、ちゃんと返して。これがないと眠れないの。",
      chinese: "玩偶要好好还给我。没有它我睡不着。",
      file: "assets/audio/v19/voice/goodnight-plush.mp3",
      expression: "startled",
      reaction: "玩偶要还给我……睡觉需要它。",
      frame: "goodnight-hug",
    },
    "goodnight-book": {
      id: "goodnight-book",
      scene: "晚安",
      label: "下次再看",
      japanese: "本はここに置いておく。続きは、また今度。",
      chinese: "书就放在这里。下次再看后面。",
      file: "assets/audio/v19/voice/goodnight-book.mp3",
      expression: "peek",
      reaction: "书签放好了……下次继续。",
      frame: "goodnight-yawn",
    },
    "goodnight-knock-next": {
      id: "goodnight-knock-next",
      scene: "晚安",
      label: "下次也要敲门",
      japanese: "おやすみ。次も……ちゃんとノックしてね。",
      chinese: "晚安。下次也要……好好敲门哦。",
      file: "assets/audio/v19/voice/goodnight-knock-next.mp3",
      expression: "shy",
      reaction: "晚安……下次也要好好敲门。",
      frame: "goodnight-wave",
    },
  },
  cinematicFoley: {
    "door-knock-soft": {
      id: "door-knock-soft",
      label: "轻敲木门",
      file: "assets/audio/v19/foley/door-knock-soft.mp3",
    },
    "door-handle-turn": {
      id: "door-handle-turn",
      label: "门把转动",
      file: "assets/audio/v19/foley/door-handle-turn.mp3",
    },
    "door-open-gentle": {
      id: "door-open-gentle",
      label: "木门轻开",
      file: "assets/audio/v19/foley/door-open-gentle.mp3",
    },
    "room-stylus-glide": {
      id: "room-stylus-glide",
      label: "笔尖划过数位板",
      file: "assets/audio/v19/foley/room-stylus-glide.mp3",
    },
    "room-chair-slide": {
      id: "room-chair-slide",
      label: "椅子轻移",
      file: "assets/audio/v19/foley/room-chair-slide.mp3",
    },
    "room-curtain-slide": {
      id: "room-curtain-slide",
      label: "窗帘布料滑动",
      file: "assets/audio/v19/foley/room-curtain-slide.mp3",
    },
    "secrets-headphones-set": {
      id: "secrets-headphones-set",
      label: "耳机放下",
      file: "assets/audio/v19/foley/secrets-headphones-set.mp3",
    },
    "secrets-paper-lift": {
      id: "secrets-paper-lift",
      label: "稿纸掀起",
      file: "assets/audio/v19/foley/secrets-paper-lift.mp3",
    },
    "secrets-drawer-latch": {
      id: "secrets-drawer-latch",
      label: "抽屉锁扣",
      file: "assets/audio/v19/foley/secrets-drawer-latch.mp3",
    },
    "wardrobe-hanger-slide": {
      id: "wardrobe-hanger-slide",
      label: "衣架滑动",
      file: "assets/audio/v19/foley/wardrobe-hanger-slide.mp3",
    },
    "wardrobe-sleeve-rustle": {
      id: "wardrobe-sleeve-rustle",
      label: "袖口布料",
      file: "assets/audio/v19/foley/wardrobe-sleeve-rustle.mp3",
    },
    "wardrobe-ribbon-rustle": {
      id: "wardrobe-ribbon-rustle",
      label: "丝带轻响",
      file: "assets/audio/v19/foley/wardrobe-ribbon-rustle.mp3",
    },
    "gallery-book-open": {
      id: "gallery-book-open",
      label: "画册打开",
      file: "assets/audio/v19/foley/gallery-book-open.mp3",
    },
    "gallery-page-turn": {
      id: "gallery-page-turn",
      label: "单页翻动",
      file: "assets/audio/v19/foley/gallery-page-turn.mp3",
    },
    "gallery-photo-slide": {
      id: "gallery-photo-slide",
      label: "画纸滑动",
      file: "assets/audio/v19/foley/gallery-photo-slide.mp3",
    },
    "drawing-stylus-line": {
      id: "drawing-stylus-line",
      label: "数位笔短线",
      file: "assets/audio/v19/foley/drawing-stylus-line.mp3",
    },
    "drawing-paper-cover": {
      id: "drawing-paper-cover",
      label: "稿纸盖住",
      file: "assets/audio/v19/foley/drawing-paper-cover.mp3",
    },
    "drawing-sheet-push": {
      id: "drawing-sheet-push",
      label: "画纸推近",
      file: "assets/audio/v19/foley/drawing-sheet-push.mp3",
    },
    "goodnight-plush-squeeze": {
      id: "goodnight-plush-squeeze",
      label: "玩偶轻压",
      file: "assets/audio/v19/foley/goodnight-plush-squeeze.mp3",
    },
    "goodnight-book-close": {
      id: "goodnight-book-close",
      label: "书本合上",
      file: "assets/audio/v19/foley/goodnight-book-close.mp3",
    },
    "goodnight-latch": {
      id: "goodnight-latch",
      label: "房门锁舌轻合",
      file: "assets/audio/v19/foley/goodnight-latch.mp3",
    },
  },
  heroExpressions: {
    peek: {
      ...v19Portrait("door-peek"),
      alt: "银白长发、蓝眼睛的纱雾穿着粉色猫耳家居服，握着半掩的卧室门安静偷看",
    },
    startled: {
      ...v19Portrait("door-startled"),
      alt: "听见敲门后，纱雾睁大蓝眼睛露出突然受惊的可爱表情",
    },
    shy: {
      ...v19Portrait("door-open-smile"),
      alt: "认出来访者后，纱雾握着门边脸红地害羞微笑",
    },
    proud: {
      ...v19Portrait("door-open-smile"),
      alt: "纱雾握着门边，露出害羞又有一点得意的可爱微笑",
    },
  },
  outfits: {
    home: {
      name: "宽松运动家居服",
      ...v18Portrait("outfit-home"),
      alt: "纱雾穿宽松粉色运动外套和奶油色运动裤，坐在床边害羞微笑",
      description:
        "袖子要够长，裤脚要够软。窝在房间里画画的时候，这样才最安心。",
      time: "午后 15:20",
      expression: "shy",
      reaction: "这套……最不会分心。",
    },
    artist: {
      name: "格纹画稿睡衣",
      ...v18Portrait("outfit-artist-night"),
      alt: "纱雾穿蓝白格长袖睡衣和长裤，戴着绘图手套在月光下认真画画",
      description:
        "蓝白格睡衣、绘图手套和不会掉下去的软拖鞋——熬夜画稿模式，准备完成。",
      time: "深夜 00:47",
      expression: "proud",
      reaction: "今、今晚一定画得完。",
    },
    outing: {
      name: "薄荷水手外套",
      ...v18Portrait("outfit-outing-sailor"),
      alt: "纱雾穿水手领裙装、薄荷色针织外套和深色长袜，抱着棕色书包站在门口",
      description:
        "水手领、厚厚的薄荷针织和能挡住紧张的书包。真的要出门时，会在门口多站一会儿。",
      time: "早上 08:10",
      expression: "startled",
      reaction: "外、外面的人不会很多吧？",
    },
    bedtime: {
      name: "草莓睡前服",
      ...v18Portrait("outfit-bedtime"),
      alt: "深夜里，纱雾穿奶油粉草莓长袖睡衣和长裤，侧躺在床上用数位板继续画画",
      description:
        "已经换好睡衣，却还舍不得放下最后一笔。数位板垫在枕头上，画到眼睛发困才肯保存。",
      time: "凌晨 01:13",
      expression: "shy",
      reaction: "再画这一小块就睡……真、真的。",
    },
    hooded: {
      name: "猫耳连帽毯",
      ...v18Portrait("outfit-hooded-blanket"),
      alt: "雨夜里，纱雾裹着薄荷灰猫耳连帽毯，穿长裤和暖袜坐在地毯上认真校对画稿",
      description:
        "帽子拉低一点，袖子再长一点，就能把雨声和截稿压力都挡在外面；该改的线却一笔也不会漏。",
      time: "雨夜 21:36",
      expression: "proud",
      reaction: "这样就不冷……也不会被看到太多。",
    },
  },
  visitStages: [
    {
      id: "first",
      maxVisits: 1,
      note: "第一次站在门外",
      hanger: "正在画画",
      lead: "门里传来很轻的脚步声。",
      quote: "“先敲门……我才会开。”",
      reaction: "……门外是谁？",
      openLead: "她认出来访者以后，脸更红了。",
      openQuote: "“只、只可以安静地待一会儿。”",
      openReaction: "只可以安静地待一会儿。",
      secretMessage: "“谢谢你没有催我开门。下次……也可以来。”",
    },
    {
      id: "familiar",
      maxVisits: 3,
      note: "她已经认得这阵脚步声",
      hanger: "还是要先敲门",
      lead: "你还没出声，门后的脚步就停近了一点。",
      quote: "“又来了……还是要先敲门。”",
      reaction: "又来了……我已经听见了。",
      openLead: "她这次没有再问门外是谁。",
      openQuote: "“进来吧……位置还是留在那里。”",
      openReaction: "位置还是留在那里……不要靠得太近。",
      secretMessage: "“你真的又来了……那下次，也不用站得那么远。”",
    },
    {
      id: "close",
      maxVisits: Infinity,
      note: "门缝比上次多留了一点",
      hanger: "有一张画想给你看",
      lead: "门缝在你靠近以前，就先亮起了一线暖光。",
      quote: "“我刚好有张画……想先听你的感想。”",
      reaction: "来得正好……有一张画想先给你看。",
      openLead: "画稿已经被悄悄放在桌边。",
      openQuote: "“我没有等很久……进来吧。”",
      openReaction: "才没有一直等……只是刚好画完。",
      secretMessage: "“这次不用等我把留言藏好。反正……你还会再来。”",
    },
  ],
  voiceLines: {
    welcome: {
      id: "welcome",
      scene: "房门口",
      replies: [
        {
          id: "welcome-home",
          label: "认出你了",
          japanese: "お、おかえり……ノック、一回でいいから。",
          chinese: "欢、欢迎回来……敲一次就够了。",
          file: "assets/audio/v4/welcome-home.mp3",
          expression: "shy",
          reaction: "欢、欢迎回来……敲一次我就听见了。",
        },
        {
          id: "welcome-close",
          label: "悄悄让开一点",
          japanese: "入ってもいいけど……静かにして。あと、近すぎるのは禁止。",
          chinese: "可以进来……但要安静。还有，不许靠得太近。",
          file: "assets/audio/v4/welcome-close.mp3",
          expression: "shy",
          reaction: "可以进来……不许突然靠近。",
        },
        {
          id: "welcome-glad",
          label: "藏不住一点开心",
          japanese: "来たんだ……その、少しだけ嬉しい。",
          chinese: "你来了呀……那个，只有一点点开心。",
          file: "assets/audio/v4/welcome-glad.mp3",
          expression: "shy",
          reaction: "只、只有一点点开心……不要笑。",
        },
        {
          id: "welcome-door-gap",
          label: "给门留一条小缝",
          japanese: "ドア、少しだけ開けておく。……見つめすぎないで。",
          chinese: "门给你留一点缝……不许一直盯着看。",
          file: "assets/audio/v4/welcome-door-gap.mp3",
          expression: "shy",
          reaction: "门缝只留这么大……不许一直看我。",
        },
      ],
      guardedReplies: [
        {
          id: "welcome-knock",
          label: "被连续催门",
          japanese: "聞こえてる……そんなに急かしたら、開けないから。",
          chinese: "我听见了……再那么催我，我就不开门了。",
          file: "assets/audio/v4/welcome-knock.mp3",
          expression: "startled",
          reaction: "连着催门的话……真的不开了。",
        },
        {
          id: "welcome-waiting",
          label: "被催得有点嘴硬",
          japanese: "遅い……べ、別に待ってたわけじゃないけど。",
          chinese: "好慢……我、我又没有在等你。",
          file: "assets/audio/v4/welcome-waiting.mp3",
          expression: "proud",
          reaction: "一直敲什么……才、才没有在等你。",
        },
      ],
    },
    drawing: {
      id: "drawing",
      scene: "画桌旁",
      replies: [
        {
          id: "drawing-stay-still",
          label: "偷偷拿你当参考",
          japanese: "動かないで。いま、手の形が難しいの。",
          chinese: "别动。我正在画……最难画的手。",
          file: "assets/audio/v4/drawing-stay-still.mp3",
          expression: "proud",
          reaction: "别动……手的形状画歪了就怪你。",
        },
        {
          id: "drawing-first-look",
          label: "答应先给你看",
          japanese: "あと一枚だけ。描けたら……最初に見せてあげる。",
          chinese: "只差一张。画好以后……第一个给你看。",
          file: "assets/audio/v4/drawing-first-look.mp3",
          expression: "shy",
          reaction: "只、只给你先看一眼。",
        },
        {
          id: "drawing-one-second",
          label: "准你偷看一秒",
          japanese: "この線、うまくいった。……一秒だけなら、見てもいいよ。",
          chinese: "这条线画得很好……只看一秒的话，可以哦。",
          file: "assets/audio/v4/drawing-one-second.mp3",
          expression: "proud",
          reaction: "就、就一秒……这条线画得还不错吧。",
        },
        {
          id: "drawing-stay-near",
          label: "允许你安静陪着",
          japanese:
            "隣にいてもいいけど、静かにして。……描き終わったら呼ぶから。",
          chinese: "可以待在旁边，但要安静……画完我会叫你的。",
          file: "assets/audio/v4/drawing-stay-near.mp3",
          expression: "shy",
          reaction: "可以待在旁边……画完以后我会叫你。",
        },
      ],
      guardedReplies: [
        {
          id: "drawing-no-peeking",
          label: "偷看得太急",
          japanese: "まだ途中。勝手に覗いたら……追い出すから。",
          chinese: "还没画完。敢擅自偷看……就把你赶出去。",
          file: "assets/audio/v4/drawing-no-peeking.mp3",
          expression: "startled",
          reaction: "还在画……一直偷看的话要赶人了。",
        },
        {
          id: "drawing-opinion",
          label: "追问得太多次",
          japanese: "見たいなら、感想ちゃんと言って。『かわいい』だけは禁止。",
          chinese: "想看的话，就要认真说感想。只说“可爱”不算。",
          file: "assets/audio/v4/drawing-opinion.mp3",
          expression: "proud",
          reaction: "问这么多次……那就要认真说感想。",
        },
      ],
    },
    like: {
      id: "like",
      scene: "画册旁",
      replies: [
        {
          id: "like-another",
          label: "藏不住一点得意",
          japanese: "そ、そんなに好き？……じゃあ、もう一枚だけ。",
          chinese: "有、那么喜欢吗？……那就，再给你看一张。",
          file: "assets/audio/v4/like-another.mp3",
          expression: "proud",
          reaction: "只、只多给你看一张。",
        },
        {
          id: "like-really",
          label: "确认你不是哄她",
          japanese: "本当に？　お世辞だったら……もう見せないから。",
          chinese: "真的？要是客套话……以后就不给你看了。",
          file: "assets/audio/v4/like-really.mp3",
          expression: "shy",
          reaction: "不许只是哄我……我会当真的。",
        },
        {
          id: "like-again",
          label: "想再听一次",
          japanese: "褒めても何も出ない……もう一回言うなら、聞くけど。",
          chinese: "就算夸我也没有奖励……不过要再说一次，我会听。",
          file: "assets/audio/v4/like-again.mp3",
          expression: "shy",
          reaction: "再、再说一次也不是不可以。",
        },
        {
          id: "like-gift",
          label: "把画推给你",
          japanese: "これ、あげる。折ったら……もう描いてあげない。",
          chinese: "这个送给你。弄皱的话……以后就不给你画了。",
          file: "assets/audio/v4/like-gift.mp3",
          expression: "proud",
          reaction: "弄皱的话……以后真的不画给你了。",
        },
        {
          id: "like-noticed",
          label: "发现你看得很认真",
          japanese: "そこ、気づいたんだ……ちゃんと見てくれてたんだね。",
          chinese: "你注意到那里了呀……真的有认真看呢。",
          file: "assets/audio/v4/like-noticed.mp3",
          expression: "shy",
          reaction: "连那里都注意到了……原来真的有认真看。",
        },
      ],
    },
    goodnight: {
      id: "goodnight",
      scene: "晚安以前",
      replies: [
        {
          id: "goodnight-together",
          label: "画师式催睡",
          japanese: "もう遅い。寝ないと、明日の線がぶれるよ。",
          chinese: "已经很晚了。不睡的话，明天画线会手抖哦。",
          file: "assets/audio/v4/goodnight-together.mp3",
          expression: "shy",
          reaction: "熬夜的话，明天连直线都画不好。",
        },
        {
          id: "goodnight-sleep",
          label: "认真催你睡觉",
          japanese: "明日も来るなら……今日はちゃんと寝て。",
          chinese: "如果明天还要来……今天就好好睡觉。",
          file: "assets/audio/v4/goodnight-sleep.mp3",
          expression: "proud",
          reaction: "不许偷偷熬夜，我会知道的。",
        },
        {
          id: "goodnight-one-minute",
          label: "舍不得赶你走",
          japanese: "電気を消したら帰って。……あと一分だけなら、いていい。",
          chinese: "关灯后就回去。……再待一分钟也可以。",
          file: "assets/audio/v4/goodnight-one-minute.mp3",
          expression: "shy",
          reaction: "只有一分钟……不许偷偷加时。",
        },
        {
          id: "goodnight-dream",
          label: "答应明天继续",
          japanese: "おやすみ。明日、続き見せてあげる……たぶん。",
          chinese: "晚安。明天给你看后续……大概。",
          file: "assets/audio/v4/goodnight-dream.mp3",
          expression: "shy",
          reaction: "明天……大概会给你看下一页。",
        },
        {
          id: "goodnight-answer",
          label: "等你回一句晚安",
          japanese:
            "おやすみって言ったら、ちゃんと返して。……聞いてから寝るから。",
          chinese: "我说晚安以后，你也要好好回答……听见了我才睡。",
          file: "assets/audio/v4/goodnight-answer.mp3",
          expression: "shy",
          reaction: "要、要等你也说完晚安……我才会睡。",
        },
      ],
    },
  },
  reactions: {
    idle: { expression: "peek", label: "纱雾的反应", text: "……门外是谁？" },
    knock: {
      expression: "startled",
      label: "听见敲门",
      text: "咿——！你、你什么时候来的？",
    },
    open: {
      expression: "shy",
      label: "门打开以后",
      text: "只可以安静地待一会儿。",
    },
    secret: {
      expression: "startled",
      label: "秘密被发现",
      text: "那、那个也要看吗？",
    },
    repeat: {
      expression: "proud",
      label: "已经看过啦",
      text: "记得这么清楚……还算合格。",
    },
    unlocked: {
      expression: "shy",
      label: "五枚猫爪集齐",
      text: "留言只许你一个人看。",
    },
    gallery: {
      expression: "startled",
      label: "画稿翻页中",
      text: "慢一点，纸角会折到的。",
    },
    fortune: {
      expression: "shy",
      label: "纸条换了一张",
      text: "这句……也送给你。",
    },
    voiceError: {
      expression: "peek",
      label: "声音没有播放",
      text: "字幕还在，先看这里也可以。",
    },
  },
  galleryChapters: [
    {
      id: "start",
      title: "第一章 · 偷偷开始",
      short: "偷偷开始",
      start: 0,
      end: 3,
    },
    {
      id: "closer",
      title: "第二章 · 把画推近",
      short: "把画推近",
      start: 4,
      end: 7,
    },
    {
      id: "praise",
      title: "第三章 · 等一句夸奖",
      short: "等一句夸奖",
      start: 8,
      end: 10,
    },
  ],
  gallery: [
    {
      id: "bed-drawing",
      ...v18Scene("gallery-bed-drawing"),
      alt: "银白长发的女孩穿粉色猫耳家居服，盘腿坐在床上用数位板画画，被发现后害羞抬眼",
      title: "被抓到在床上画画",
      note: "她原本把数位板藏在膝盖上。听见你靠近，只来得及红着脸抬头：“不许笑……这里比较舒服而已。”",
      expression: "startled",
      reaction: "我、我只是觉得床上比较暖……不许笑。",
    },
    {
      id: "blanket-fort",
      ...v18Scene("gallery-blanket-fort"),
      alt: "银白长发的女孩躲在被子搭成的小帐篷里画画，红着脸从帘边递出一张小猫速写",
      title: "被窝画室只开一条缝",
      note: "她用被子围出一间更小的画室，只把帘子拉开一点点。小猫速写先从缝里递出来，藏在袖口后的声音轻得几乎听不见：“画、画可以先看……”",
      expression: "shy",
      reaction: "帐篷里只能坐一个人……画可以先借你看。",
    },
    {
      id: "stream-wave",
      ...v18Scene("gallery-stream-wave"),
      alt: "银白长发的女孩戴着猫耳耳机坐在数位板前进行安静的绘画直播，用袖口挡住红脸小幅挥手",
      title: "直播开始前的小小挥手",
      note: "进入画师模式时，她盯着线稿比谁都认真。发现镜头还开着，才用袖口挡住脸，飞快挥了一下手：“只、只是在确认画面。”",
      expression: "startled",
      reaction: "刚才不算打招呼……只是确认镜头。",
    },
    {
      id: "show-drawing",
      ...v18Scene("gallery-show-drawing"),
      alt: "银白长发的女孩跪坐在床边，红着脸把画着可爱角色的速写本举给来访者看",
      title: "只给你看三秒",
      note: "画纸举得很认真，视线却躲到了旁边。“看、看完就要说感想……不许只点头。”",
      expression: "shy",
      reaction: "三秒……已经到了。所、所以感想呢？",
    },
    {
      id: "pillow-offer",
      ...v18Scene("gallery-pillow-offer"),
      alt: "银白长发的女孩穿蓝白格睡衣，抱着粉色猫咪靠枕，从靠枕后把一张小猫画递给来访者",
      title: "躲在靠枕后把画递给你",
      note: "大半张脸都藏起来了，画却认真地伸到你面前。“只、只许看画……不许一直看我。”",
      expression: "shy",
      reaction: "只许看画，不许看我……感想还是要说。",
    },
    {
      id: "door-note",
      ...v18Scene("gallery-door-note"),
      alt: "银白长发的女孩藏在半开的卧室门后，脸红着从门缝递出一张画有小猫的卡片",
      title: "谢谢要从门缝里递出来",
      note: "亲口说出口还是太难了，于是她把认真画好的小猫卡片从门缝推给你。等你接稳，门后才传来一句：“那、那只小猫不许笑。”",
      expression: "shy",
      reaction: "卡片收好就行……不许笑上面那只小猫。",
    },
    {
      id: "desk-night",
      ...v18Scene("gallery-desk-night"),
      alt: "深夜里，银白长发的女孩趴在数位板前认真画画，桌灯照亮画稿",
      title: "认真起来就忘了害羞",
      note: "嘴上说着不许偷看，真正画起来以后，连门边的脚步声都听不见了。",
      expression: "proud",
      reaction: "这一笔很重要……等、等画完再和你说话。",
    },
    {
      id: "sketch-sort",
      ...v18Scene("gallery-sketch-sort"),
      alt: "银白长发的女孩穿粉色长袖家居服坐在地毯上整理速写，抱住一张画稿并害羞地把另一张推向来访者",
      title: "最喜欢的那张先藏住",
      note: "散在地毯上的草稿被分成好多小堆。她把最喜欢的一张紧紧抱住，却又把另一张悄悄推向你：“这张……可以替我保管一下。”",
      expression: "shy",
      reaction: "最喜欢的先不行……这张可以替我保管。",
    },
    {
      id: "sketchbook-hide",
      ...v18Scene("gallery-sketchbook-hide"),
      alt: "银白长发的女孩躲在大画册后，只露出一双明亮的蓝眼睛",
      title: "被看太久就藏起来",
      note: "画册挡住了大半张脸，但那双眼睛已经把“我知道你还在看”全都说出来了。",
      expression: "startled",
      reaction: "看、看太久了……下一页要先征得同意。",
    },
    {
      id: "awaiting-praise",
      ...v18Scene("gallery-awaiting-praise"),
      alt: "银白长发的女孩抱膝坐在床上，速写本朝向来访者，脸红着等待评价",
      title: "装作没有在等夸奖",
      note: "她把画留在最显眼的位置，自己却缩进了宽大的袖口里。“我、我没有催你……慢慢看也行。”",
      expression: "shy",
      reaction: "没有在等……但你可以再说具体一点。",
    },
    {
      id: "goodnight",
      ...v18Scene("gallery-goodnight-clean"),
      alt: "月光下，银白长发的女孩蜷坐在窗边抱着猫咪玩偶，露出困倦的微笑",
      title: "今天的最后一页",
      note: "稿子保存好，窗帘留一条缝，再抱住最软的玩偶。临睡前，她还是小声补了一句：“明天……也可以来。”",
      expression: "shy",
      reaction: "明天再翻一页……今天要好好睡觉。",
    },
  ],
  secrets: {
    tablet: {
      label: "数位板",
      hint: "她的手刚从画面中央那块最常碰的黑色板子旁收回来。",
      text: "快捷键都设成单手能按到，因为另一只手常常要抱着靠枕。",
    },
    headphones: {
      label: "耳机",
      hint: "画线稿以前，她总会先看一眼画面左上方的耳机。",
      text: "画线稿时会循环同一张安静的歌单，音量永远只开到三格。",
    },
    manuscript: {
      label: "轻小说稿件",
      hint: "桌面左下角那叠纸的页边，好像画了比正文更多的东西。",
      text: "页边画满了表情草稿。比起剧情批注，她更先注意角色有没有好好笑出来。",
    },
    plush: {
      label: "猫咪玩偶",
      hint: "她卡住的时候，视线会飘向画面右上方那只软绵绵的家伙。",
      text: "不顺利的时候会被抱得很紧。顺利的时候，也一样。",
    },
    drawer: {
      label: "上锁抽屉",
      hint: "最不肯解释的东西，通常被她推到桌子的右下角。",
      text: "钥匙藏在薄荷色铅笔盒底下。不过，要集齐五枚猫爪才可以打开。",
    },
  },
  drawingStory: {
    frames: {
      focus: {
        ...v18Scene("studio-focus-clean"),
        alt: "纱雾在夜色里的画桌前低头用数位板认真画线稿",
      },
      blink: {
        ...v18Scene("studio-blink-clean"),
        alt: "纱雾低头画线时轻轻眨了一下眼睛",
      },
      shy: {
        ...v18Scene("studio-shy-clean"),
        alt: "被认真夸奖后，纱雾脸红着用长袖袖口遮住嘴角",
      },
      reveal: {
        ...v18Scene("studio-reveal-clean"),
        alt: "纱雾露出害羞又有一点得意的表情，把刚完成的小猫画推到桌边",
      },
    },
    peekReactions: [
      {
        expression: "startled",
        label: "偷看被抓到了",
        text: "咿——！这、这张还没画完，不许突然凑过来。",
      },
      {
        expression: "shy",
        label: "只露出一小角",
        text: "……只能看这里。再多一点就要等我画完。",
      },
      {
        expression: "proud",
        label: "她还是推近了一点",
        text: "都说了没画完……不过，这根线可以先给你看。",
      },
    ],
    quietBeats: [
      {
        at: 20000,
        time: "安静地待了二十秒",
        title: "她重新描细了一根线。",
        line: "袖口擦过数位板边缘。她没有抬头，只把旁边那把椅子又往外挪了半格。",
        frame: "focus",
      },
      {
        at: 45000,
        time: "房间安静了四十五秒",
        title: "她终于确认你还在。",
        line: "“……你还在啊。”声音很轻，像是怕一说大声，这段安静就会结束。",
        frame: "shy",
      },
      {
        at: 75000,
        time: "一起待过一分多钟",
        title: "画稿被悄悄推近了一点。",
        line: "她把屏幕转过来一点点，又立刻盯回笔尖：“接下来画什么……你可以帮我选。”",
        frame: "shy",
      },
    ],
    presence: {
      quiet: {
        label: "安静坐在旁边",
        detail: "不催她，也不一直盯着屏幕",
        line: "……这样就好。你可以看，但不许突然凑过来。",
        memory: "安静坐在旁边",
      },
      help: {
        label: "问她哪里需要帮忙",
        detail: "等她自己把犹豫说出来",
        line: "那、那就帮我决定画什么。只准认真选。",
        memory: "先问我哪里需要帮忙",
      },
      distance: {
        label: "把椅子挪远一点",
        detail: "给她留出不会被盯着看的距离",
        line: "不用那么远……会看不清的。靠回来一点也可以。",
        memory: "还特意把椅子挪远了一点",
      },
    },
    subjects: {
      door: {
        label: "门缝看月亮的小猫",
        detail: "明明好奇，却只肯先探出半张脸",
        ...v18Scene("drawing-door-moon"),
        alt: "奶油稿纸上，一只小猫从半开的房门后看向月亮和星星的铅笔水彩画",
        line: "门只开这么大……但月亮还是看得见。",
        stageNote: "她先画了一条很窄的门缝，又在外面留了一轮月亮。",
      },
      blanket: {
        label: "被窝里画星星的小猫",
        detail: "躲进最小的画室，还是很认真地下笔",
        ...v18Scene("drawing-blanket-star"),
        alt: "奶油稿纸上，一只小猫躲在被窝帐篷里用铅笔画星星的铅笔水彩画",
        line: "被子里面比较安静……画线也不会抖。",
        stageNote: "她把被子画成一间很小的画室，只给笔尖留了出口。",
      },
      pencil: {
        label: "抱着大铅笔的小猫",
        detail: "看起来软绵绵，抱住画笔时却很认真",
        ...v18Scene("drawing-pencil-stars"),
        alt: "奶油稿纸上，一只小猫抱住一支大铅笔，周围散着三颗小星星的铅笔水彩画",
        line: "笔不能放开。灵感跑掉的话……很难抓回来。",
        stageNote: "她把铅笔画得比小猫还大，爪子却抱得很稳。",
      },
    },
    palettes: {
      strawberry: {
        label: "草莓黄昏",
        detail: "暖粉、纸灯和一点点晚霞",
        className: "palette-strawberry",
        line: "暖一点也可以……但、不许说是因为我喜欢粉色。",
      },
      mint: {
        label: "薄荷雨夜",
        detail: "安静的薄荷青压住窗外雨声",
        className: "palette-mint",
        line: "这个颜色很安静。画久一点，眼睛也不会累。",
      },
      moon: {
        label: "银蓝月光",
        detail: "银白、月蓝和很淡的夜色",
        className: "palette-moon",
        line: "像窗帘没有完全拉紧的时候……就用这个。",
      },
    },
    praises: {
      soft: {
        label: "线条看起来很软",
        detail: "连门和铅笔都没有尖锐的感觉",
        memory: "线条看起来很软",
        line: "你连线条都认真看了……那、那我不改这一笔了。",
      },
      eyes: {
        label: "小猫的眼神很认真",
        detail: "害羞归害羞，它真的很喜欢画画",
        memory: "小猫的眼神很认真",
        line: "看得出来吗？我画那双眼睛……改了很多次。",
      },
      lamp: {
        label: "配色像一盏小夜灯",
        detail: "很安静，但不会让人觉得孤单",
        memory: "配色像一盏小夜灯",
        line: "小夜灯……这个说法，我会写在稿纸背面。",
      },
    },
  },
  livingRoom: {
    voices: {
      "room-desk-intro": {
        scene: "画桌旁",
        label: "留给你的座位",
        japanese:
          "ここ、私のいちばん落ち着く場所。隣なら、少しだけ空いてるよ。",
        chinese: "这里是我最安心的地方。旁边的话……还空着一点。",
        file: "assets/audio/v8/voice/room-desk-intro.mp3",
        expression: "shy",
        reaction: "只是椅子刚好没有推回去……不是特意留的。",
      },
      "room-desk-pencil": {
        scene: "画桌旁",
        label: "最后一笔",
        japanese: "この線、やっと決まった。ちょっとだけ見ていいよ。",
        chinese: "这根线终于定下来了。只给你看一点点。",
        file: "assets/audio/v8/voice/room-desk-pencil.mp3",
        expression: "proud",
        reaction: "她把刚画好的轮廓转过来一点，手指仍压着画纸的一角。",
      },
      "room-desk-eye": {
        scene: "画桌旁",
        label: "只看眼睛",
        japanese: "目のところだけ。ほかまで見たら隠すから。",
        chinese: "只许看眼睛。要是看到别的地方，我就藏起来。",
        file: "assets/audio/v8/voice/room-desk-eye.mp3",
        expression: "startled",
        reaction: "她盯着你的视线，像真的随时会把数位板抱回去。",
      },
      "room-desk-stay": {
        scene: "画桌旁",
        label: "再画一张",
        japanese: "まだいてくれたんだ。じゃあ、あと一枚だけ。",
        chinese: "你还在呀……那就再画一张。",
        file: "assets/audio/v8/voice/room-desk-stay.mp3",
        expression: "shy",
        reaction: "保存完成以后，她没有催你离开，只是又新建了一张画布。",
      },
      "room-bed-intro": {
        scene: "床边",
        label: "床上的小画室",
        japanese: "ベッドでも描けるから。さぼってるんじゃないよ。",
        chinese: "在床上也能画。所以我才不是在偷懒。",
        file: "assets/audio/v8/voice/room-bed-intro.mp3",
        expression: "proud",
        reaction: "她把数位板摆得更正了一点，认真证明这里也是工作区。",
      },
      "room-bed-blanket": {
        scene: "床边",
        label: "接住毯角",
        japanese: "ありがとう。毛布、落ちるところだった。",
        chinese: "谢谢。毯子刚才差点就掉下去了。",
        file: "assets/audio/v8/voice/room-bed-blanket.mp3",
        expression: "shy",
        reaction: "毯角被仔细收回脚边，旁边也悄悄空出了半个靠枕。",
      },
      "room-bed-fort": {
        scene: "床边",
        label: "小帐篷的缝",
        japanese: "この隙間は換気用。のぞくためじゃないから。",
        chinese: "这条缝是用来通风的。才不是让你偷看的。",
        file: "assets/audio/v8/voice/room-bed-fort.mp3",
        expression: "startled",
        reaction: "帘边的缝没有合上，反而又露出了一点画纸。",
      },
      "room-bed-pillow": {
        scene: "床边",
        label: "借你靠枕",
        japanese: "そのクッション、少しだけ貸してあげる。",
        chinese: "那个靠枕……可以借你一会儿。",
        file: "assets/audio/v8/voice/room-bed-pillow.mp3",
        expression: "shy",
        reaction: "最软的猫咪靠枕被推过来，她自己却先躲回了袖口后面。",
      },
      "room-wardrobe-intro": {
        scene: "衣橱边",
        label: "替她选一件",
        japanese: "どっちがいいと思う？ 笑わないなら、聞いてあげる。",
        chinese: "你觉得哪件好？只要不笑我……就听听你的意见。",
        file: "assets/audio/v8/voice/room-wardrobe-intro.mp3",
        expression: "shy",
        reaction: "两种颜色被重新举到一样高，她终于肯把选择分给你一点。",
      },
      "room-wardrobe-hanger": {
        scene: "衣橱边",
        label: "扶稳衣架",
        japanese: "助かった。ハンガーの音、びっくりするから。",
        chinese: "帮大忙了。衣架的声音总会吓我一跳。",
        file: "assets/audio/v8/voice/room-wardrobe-hanger.mp3",
        expression: "shy",
        reaction: "木衣架安静下来以后，她才慢慢松开一直绷着的肩膀。",
      },
      "room-wardrobe-hood": {
        scene: "衣橱边",
        label: "猫耳连帽毯",
        japanese: "これは可愛いんじゃなくて、暖かいだけ。",
        chinese: "这件才不是为了可爱，只是比较暖而已。",
        file: "assets/audio/v8/voice/room-wardrobe-hood.mp3",
        expression: "startled",
        reaction: "嘴上说着只是保暖，露出来的猫耳却还在轻轻晃。",
      },
      "room-wardrobe-choice": {
        scene: "衣橱边",
        label: "粉色还是薄荷",
        japanese: "ピンクとミント、どっちがいい？ ちゃんと選んで。",
        chinese: "粉色和薄荷色，哪件好？要认真选。",
        file: "assets/audio/v8/voice/room-wardrobe-choice.mp3",
        expression: "proud",
        reaction: "她等着你的答案，没有再偷偷把薄荷色那件藏到后面。",
      },
      "room-window-intro": {
        scene: "窗台",
        label: "窗边的安静",
        japanese: "窓のそばは静か。雨も、ここなら遠くに聞こえる。",
        chinese: "窗边很安静。连雨声在这里听起来也很远。",
        file: "assets/audio/v8/voice/room-window-intro.mp3",
        expression: "shy",
        reaction: "她抱紧猫咪玩偶，给你留出了能一起看月亮的位置。",
      },
      "room-window-latch": {
        scene: "窗台",
        label: "关小窗缝",
        japanese: "これくらいの隙間なら、雨の音も小さいね。",
        chinese: "窗缝留这么大的话，雨声也会小一点呢。",
        file: "assets/audio/v8/voice/room-window-latch.mp3",
        expression: "shy",
        reaction: "雨声退到玻璃外面，月光仍从没有关严的窗帘边落进来。",
      },
      "room-window-moon": {
        scene: "窗台",
        label: "两个月亮",
        japanese: "絵の月と本物の月、並べても変じゃないよね。",
        chinese: "画里的月亮和真的月亮摆在一起，也不奇怪吧？",
        file: "assets/audio/v8/voice/room-window-moon.mp3",
        expression: "proud",
        reaction: "小猫画被靠在窗边，纸上的月亮刚好接住了外面的光。",
      },
      "room-window-close": {
        scene: "窗台",
        label: "再留一分钟",
        japanese: "今日はここまで。あと一分なら、いていいよ。",
        chinese: "今天就到这里。再待一分钟的话……可以。",
        file: "assets/audio/v8/voice/room-window-close.mp3",
        expression: "shy",
        reaction: "画册已经合上，她却没有立刻把身边的位置收回去。",
      },
      "room-weather-rain": {
        scene: "房间窗外",
        label: "雨落在窗外",
        japanese: "雨、降ってきた。窓の外だけだから、心配しないで。",
        chinese: "下雨了。不过雨只在窗外，不用担心。",
        file: "assets/audio/v8/voice/room-weather-rain.mp3",
        expression: "shy",
        reaction: "雨线只沿着窗玻璃落下，房间里的木地板仍然干燥温暖。",
      },
      "room-weather-clear": {
        scene: "房间窗外",
        label: "雨停见月",
        japanese: "雨、やんだみたい。月が見えるよ。",
        chinese: "雨好像停了。能看见月亮了。",
        file: "assets/audio/v8/voice/room-weather-clear.mp3",
        expression: "proud",
        reaction: "窗上的雨线淡下去，月光重新落在玩偶柔软的耳朵上。",
      },
    },
    phases: {
      morning: { label: "清晨", note: "窗光刚越过床沿，房间还没有完全醒。" },
      day: { label: "午后", note: "墙纸被日光照得很软，连稿纸都显得轻一点。" },
      evening: {
        label: "傍晚",
        note: "台灯先亮起来，窗外的颜色正在慢慢变深。",
      },
      night: { label: "夜里", note: "木地板已经安静下来，只剩很轻的创作声。" },
      late: { label: "深夜", note: "房间缩进一盏小灯里，她还舍不得停笔。" },
    },
    places: {
      desk: {
        label: "画桌旁",
        ...v18Scene("studio-focus-clean"),
        alt: "纱雾在暖灯与夜窗之间低头画稿，桌边放着数位板、铅笔和小猫玩偶",
        title: "先别叫她，她正画到最认真的地方。",
        line: "她把旁边的椅子留出一点，却一直装作只是忘了推回去。",
        quote: "“可以靠近……不要突然碰到数位板。”",
        ambient: [
          "笔尖还在移动，台灯把线稿照得很暖。",
          "她停下来眨了一下眼，又把刚才那根线重新描细。",
          "桌边那张共同完成的小画，被压在最不容易折到的位置。",
        ],
        autonomousFrame: {
          ...v18Scene("studio-blink-clean"),
          alt: "纱雾低头画线时轻轻眨了一下眼睛",
        },
        autonomousDuration: 145,
        action: "听她补完这一笔",
        voice: "room-desk-intro",
        voiceLabel: "听她说说画桌",
        deepLink: "#desk-secrets",
        deepLabel: "再靠近画桌一点",
        expression: "proud",
        moments: [
          {
            line: "她沿着刚才犹豫的轮廓补完最后一笔，肩膀终于松下来一点。",
            memory: "等她补完了最后一根线",
            voice: "room-desk-pencil",
            sound: "assets/audio/v14/desk-stylus-line.mp3",
          },
          {
            line: "她把数位板转过来几度，只够你看见新画好的眼睛。",
            memory: "只看了她肯转过来的那一点画稿",
            voice: "room-desk-eye",
            sound: "assets/audio/v14/desk-tablet-turn.mp3",
          },
          {
            line: "保存提示轻轻闪了一下，她才发现你一直安静坐在旁边。",
            memory: "一直等到她按下保存键",
            voice: "room-desk-stay",
            sound: "assets/audio/v14/desk-save-key.mp3",
          },
        ],
      },
      bed: {
        label: "床边",
        ...v18Scene("gallery-bed-drawing"),
        alt: "纱雾穿粉色猫耳家居服，盘腿坐在床上用数位板画画，身边堆着柔软靠枕",
        title: "床是休息的地方，也是她最小的画室。",
        line: "数位板垫在膝盖上，滑下来的被角已经快碰到地板。",
        quote: "“在床上画比较暖……这不是偷懒。”",
        ambient: [
          "靠枕被抱得慢慢陷下去，她还在检查刚画好的小猫耳朵。",
          "她用被子围出一条很窄的缝，只把画先递到外面。",
          "困意把动作放慢了，手里的笔却还没有放下。",
        ],
        action: "把滑下来的毯角递回去",
        voice: "room-bed-intro",
        voiceLabel: "听她说说床边",
        deepLink: "#gallery",
        deepLabel: "翻看床边的小片段",
        expression: "shy",
        moments: [
          {
            line: "毯角回到脚边，她愣了一下，又悄悄往旁边让出半个靠枕。",
            memory: "替她接住了滑下来的毯角",
            voice: "room-bed-blanket",
            sound: "assets/audio/v14/bed-blanket-fold.mp3",
            frame: {
              ...v18Scene("gallery-blanket-fort"),
              alt: "纱雾躲进被子搭成的小帐篷，从帘边害羞地递出一张小猫速写",
            },
          },
          {
            line: "她把小帐篷收回床角，数位板又稳稳落在膝盖上。",
            memory: "帮她把被窝小帐篷收回了床角",
            voice: "room-bed-fort",
            sound: "assets/audio/v14/bed-fort-rustle.mp3",
            frame: "base",
          },
          {
            line: "最软的猫咪靠枕被推到你这边一点，她本人却迅速躲回袖口后。",
            memory: "接住了她推过来的猫咪靠枕",
            voice: "room-bed-pillow",
            sound: "assets/audio/v14/bed-pillow-pat.mp3",
          },
        ],
      },
      wardrobe: {
        label: "衣橱边",
        ...v18Scene("wardrobe-living"),
        alt: "纱雾站在打开的木衣橱旁，害羞地比较粉色家居外套和薄荷猫耳连帽毯",
        title: "她已经比较了很久，还不肯承认自己在犹豫。",
        line: "粉色家居服比较安心，薄荷猫耳毯又足够挡住紧张的表情。",
        quote: "“我只是确认哪一件比较方便画画。”",
        ambient: [
          "衣架轻轻碰了一下，她马上伸手扶住，像怕惊动整个房间。",
          "薄荷猫耳毯被举到脸边，又因为太显眼悄悄放低。",
          "她对着两种颜色看了很久，最后先偷偷观察你的反应。",
        ],
        action: "替她扶住晃动的衣架",
        voice: "room-wardrobe-intro",
        voiceLabel: "听她说说衣橱",
        deepLink: "#wardrobe",
        deepLabel: "陪她认真选一套",
        expression: "startled",
        moments: [
          {
            line: "木衣架终于安静下来，她把差点滑落的袖子重新挂好。",
            memory: "替她扶稳了差点晃落的衣架",
            voice: "room-wardrobe-hanger",
            sound: "assets/audio/v14/wardrobe-hanger-settle.mp3",
          },
          {
            line: "她把猫耳毯往身后藏了藏，露出来的耳尖还是轻轻晃了一下。",
            memory: "发现了她藏到身后的猫耳毯",
            voice: "room-wardrobe-hood",
            sound: "assets/audio/v14/wardrobe-fabric-swish.mp3",
          },
          {
            line: "两套衣服又被并排举起来，这次她终于把选择权分给你一点。",
            memory: "认真看完了她举起来的两套衣服",
            voice: "room-wardrobe-choice",
            sound: "assets/audio/v14/wardrobe-choice.mp3",
          },
        ],
      },
      window: {
        label: "窗台",
        ...v18Scene("gallery-goodnight-clean"),
        alt: "月光下，纱雾蜷坐在窗边抱着猫咪玩偶，身旁放着合上的画册",
        title: "窗帘总会留一条缝，刚好够月光进来。",
        line: "她说那样比较容易看清时间，其实只是舍不得把夜色全部关在外面。",
        quote: "“雨小一点以后……月亮也许会出来。”",
        ambient: [
          "窗帘被风抬起一点，月光刚好落在她抱着的玩偶耳朵上。",
          "雨线沿着玻璃慢慢滑下，她在心里给每一条安排了方向。",
          "合上的画册旁边，还留着一张没有写完的晚安纸条。",
        ],
        action: "替她把窗缝关小一点",
        voice: "room-window-intro",
        voiceLabel: "听她说说窗边",
        deepLink: "#goodnight",
        deepLabel: "陪她收好今天",
        expression: "shy",
        moments: [
          {
            line: "窗缝窄了一点，雨声变轻，玩偶耳朵上的月光却还留着。",
            memory: "替她把漏进雨声的窗缝关小了一点",
            voice: "room-window-latch",
            sound: "assets/audio/v14/window-latch-slide-clean.mp3",
          },
          {
            line: "她把上次那张小猫画靠在窗边，让画里的月亮和外面排在一起。",
            memory: "陪她把画里的月亮和窗外排在一起",
            voice: "room-window-moon",
            sound: "assets/audio/v14/window-paper-slide-clean.mp3",
          },
          {
            line: "窗帘安静落下，她在合上的画册上轻轻拍了两下。",
            memory: "陪她把窗帘和今天一起收好了",
            voice: "room-window-close",
            sound: "assets/audio/v14/window-curtain-close-clean.mp3",
          },
        ],
      },
    },
  },
  goodnight: {
    doorSound: "assets/audio/v16/goodnight-door-close.mp3",
  },
  fortunes: [
    "画不完也没关系，先把今天好好收起来。",
    "今天已经很努力了，剩下的一小步留给明天。",
    "如果有点害怕，就先从门缝里看一眼。",
    "喜欢的事情不用解释很大声，认真做下去就好。",
    "晚安。明天醒来，线条会比今晚更轻一点。",
    "有人安静陪着的时候，房间就没有那么小了。",
  ],
};

CONTENT.roomExperience = {
  version: "20.0.0",
  poses: [
    "standing-neutral",
    "standing-shy",
    "standing-blink",
    "desk-focus",
    "desk-shy",
    "desk-blink",
    "reading-peek",
    "bed-hug",
    "bed-sleepy",
  ],
  scenes: {
    room: {
      label: "房间",
      line: "……你来了。坐这里就好。",
      pose: "standing-neutral",
      camera: [1, 50, 50],
      actor: [30, 0, 40, 100],
      mobileX: 50,
      actions: [
        ["走到她身边", "desk"],
        ["先看看房间", "look"],
      ],
      objects: [
        ["衣橱", "wardrobe", 14, 27],
        ["未完成的画", "drawing", 85, 38],
        ["翻翻画册", "gallery", 94, 76],
      ],
      voice: "welcome",
    },
    desk: {
      label: "画桌",
      line: "只差一点点……你要一起想想吗？",
      pose: "desk-focus",
      camera: [1.28, 86, 56],
      actor: [38, 4, 48, 96],
      mobileX: 83,
      actions: [
        ["陪她一起画", "drawing"],
        ["桌面的小秘密", "secrets"],
      ],
      objects: [
        ["看看草稿", "drawing", 84, 42],
        ["翻翻画册", "gallery", 94, 76],
        ["抽屉里的东西", "secrets", 78, 65],
      ],
      voice: "desk-arrive",
    },
    wardrobe: {
      label: "衣橱",
      line: "我只是试一下……你觉得哪一件好？",
      pose: "standing-shy",
      camera: [1.3, 14, 46],
      actor: [42, 0, 39, 100],
      mobileX: 18,
      actions: [
        ["陪她认真选", "wardrobe-story"],
        ["扶稳衣架", "wardrobe-hanger"],
      ],
      objects: [
        ["看看衣服", "outfits", 14, 30],
        ["摸摸袖口", "wardrobe-sleeve", 17, 42],
      ],
      voice: "wardrobe-compare",
    },
    bed: {
      label: "床边",
      line: "抱着它的时候，连困意都变得软软的。",
      pose: "bed-hug",
      camera: [1.25, 20, 47],
      actor: [7, 5, 46, 95],
      mobileX: 18,
      actions: [
        ["安静陪她一会儿", "quiet"],
        ["收好今天，听晚安", "goodnight"],
      ],
      objects: [
        ["抱稳猫咪玩偶", "plush", 22, 43],
        ["把毯角递回去", "blanket", 18, 58],
        ["床头的画册", "gallery", 29, 47],
      ],
      voice: "bed-plush",
    },
    window: {
      label: "窗边",
      line: "窗帘留一条缝，刚好够光照进来。",
      pose: "standing-neutral",
      camera: [1.35, 80, 29],
      actor: [27, 0, 43, 100],
      mobileX: 80,
      actions: [
        ["换一种天气", "weather"],
        ["放大看看窗外", "inspect"],
      ],
      objects: [
        ["轻轻拉一点窗帘", "curtain", 73, 20],
        ["看看窗边的小画", "memories", 79, 31],
      ],
      voice: "room-curtain",
    },
  },
  ui: {
    loadingImage: "正在准备这一处的画面……",
    imageError: "这一张暂时没有打开，先陪你留在这里。可以再试一次。",
    audioLoading: "正在准备声音……",
    audioPlaying: "正在听她说",
    audioReady: "声音已说完",
    audioMuted: "安静模式 · 字幕仍会陪着你",
    audioError: "声音暂时没有播放，台词已经留下。可以再听一次。",
    storageError: "浏览器暂时不能保存。本次浏览仍然可用，离开后可能无法恢复。",
    quietLine: "不用急着说话，也不用等到某个时刻。想继续画时，随时告诉她。",
    invitation: "……要不要过来看看？有一件小事，想听你的意见。",
    galleryDetails: {
      lines: "你慢慢看过了她反复描细的线条。",
      expression: "你停在人物的眼神上，认真看了好一会儿。",
      color: "你留意到画里柔软的配色和光。",
    },
    galleryThoughts: {
      ask: "她把画册往你这边推近了一点，愿意再说一小段。",
      favorite: "你把喜欢的这一页轻轻留了一个书签。",
    },
    wardrobePriorities: {
      comfort: "那就先看穿起来舒不舒服……袖口不能碍事。",
      color: "颜色吗？那你要认真看，不许随便点头。",
    },
    wardrobeComments: {
      soft: "袖子很适合你",
      eyes: "这个颜色很衬你的眼睛",
    },
    closedLine: "今天的纸条已经收好了。下次，再来看看她吧。",
    noMemory: "这里还没有一起留下的画。去画桌旁坐一会儿吧。",
    secretClosing: "“原来你都有认真看……那这张小纸条，也给你保管。”",
  },
  episodes: {
    drawing: {
      title: "画稿边角的小猫",
      intro: "她把一张空白稿纸留在桌边。没有标准答案，只有你们一起决定的画。",
    },
    wardrobe: {
      title: "今天穿哪一件",
      intro: "她把衣服重新挂齐，悄悄看向你。先说说你想怎么挑，再选一套。",
    },
    gallery: {
      title: "画册里没说完的话",
      intro:
        "这一页，可以多看一会儿。你注意到的地方，会成为她愿意说下去的理由。",
    },
  },
  voice: {
    welcome: {
      id: "welcome",
      scene: "迎接",
      japanese: "おかえり。今日は……どこから見たい？",
      chinese: "欢迎回来。今天……想先看看哪里？",
      file: "assets/audio/v20/voice/welcome.mp3",
      duration: 3.63102,
      expression: "neutral",
    },
    "desk-arrive": {
      id: "desk-arrive",
      scene: "走到桌边",
      japanese: "ここなら、手元が見えるでしょ。静かにしててね。",
      chinese: "在这里就能看清我手边了吧。要安静一点哦。",
      file: "assets/audio/v20/voice/desk-arrive.mp3",
      duration: 4.754286,
      expression: "neutral",
    },
    "draft-noticed": {
      id: "draft-noticed",
      scene: "草稿被看见",
      japanese: "あっ、それはまだ下書き。そんなにじっと見ないで……。",
      chinese: "啊，那还是草稿。别那么认真地盯着看……",
      file: "assets/audio/v20/voice/draft-noticed.mp3",
      duration: 4.362449,
      expression: "shy",
    },
    "draw-invite": {
      id: "draw-invite",
      scene: "邀请一起画",
      japanese: "この絵、一緒に考えてみる？　少しだけなら、頼ってもいいかな。",
      chinese: "这张画，要一起想想吗？稍微依靠你一下……可以吗？",
      file: "assets/audio/v20/voice/draw-invite.mp3",
      duration: 6.896327,
      expression: "neutral",
    },
    "quiet-company": {
      id: "quiet-company",
      scene: "安静陪伴",
      japanese: "話さなくても、大丈夫。そこにいてくれるだけでいいの。",
      chinese: "不说话也没关系。你待在那里就好。",
      file: "assets/audio/v20/voice/quiet-company.mp3",
      duration: 4.963265,
      expression: "neutral",
    },
    "theme-cat": {
      id: "theme-cat",
      scene: "选小猫主题",
      japanese: "小さな猫にしよう。耳も、しっぽも……丁寧に描きたいな。",
      chinese: "那就画只小猫吧。耳朵、尾巴……都想认真画好。",
      file: "assets/audio/v20/voice/theme-cat.mp3",
      duration: 6.791837,
      expression: "neutral",
    },
    "palette-chosen": {
      id: "palette-chosen",
      scene: "选配色",
      japanese: "この色にするんだね。じゃあ、ここから少しずつ塗ってみよう。",
      chinese: "选这个颜色呀。那就从这里开始，慢慢涂上去吧。",
      file: "assets/audio/v20/voice/palette-chosen.mp3",
      duration: 5.459592,
      expression: "neutral",
    },
    "feedback-ask": {
      id: "feedback-ask",
      scene: "询问具体感想",
      japanese: "どこが好きだった？　色とか、表情とか……ちゃんと聞きたい。",
      chinese: "你喜欢哪里呢？颜色、表情之类的……我想认真听听。",
      file: "assets/audio/v20/voice/feedback-ask.mp3",
      duration: 5.067755,
      expression: "neutral",
    },
    "artwork-reveal": {
      id: "artwork-reveal",
      scene: "展示完成稿",
      japanese: "できた。二人で決めたところ、ちゃんと絵になったね。",
      chinese: "画好了。我们一起决定的那些地方，真的变成画了呢。",
      file: "assets/audio/v20/voice/artwork-reveal.mp3",
      duration: 4.414694,
      expression: "neutral",
    },
    "draft-resume": {
      id: "draft-resume",
      scene: "恢复未完成稿",
      japanese: "この続き、覚えてるよ。残しておいたところから、また描こう。",
      chinese: "我记得这张画还没画完。就从留下来的地方，继续画吧。",
      file: "assets/audio/v20/voice/draft-resume.mp3",
      duration: 6.60898,
      expression: "shy",
    },
    "gallery-open": {
      id: "gallery-open",
      scene: "打开画册",
      japanese: "スケッチブックを開くね。まだ恥ずかしいけど……見てもいいよ。",
      chinese: "我要打开画册了。虽然还是有点害羞……但可以给你看。",
      file: "assets/audio/v20/voice/gallery-open.mp3",
      duration: 5.668571,
      expression: "neutral",
    },
    "gallery-turn": {
      id: "gallery-turn",
      scene: "慢慢翻页",
      japanese: "ページは、ゆっくりね。描き込みも、見つけてくれたら嬉しい。",
      chinese: "翻页慢一点哦。如果你能发现画里的小细节，我会很开心。",
      file: "assets/audio/v20/voice/gallery-turn.mp3",
      duration: 6.948571,
      expression: "neutral",
    },
    "gallery-favorite": {
      id: "gallery-favorite",
      scene: "问最喜欢哪张",
      japanese: "この中で、どの絵が一番好き？　理由も、少しだけ教えて。",
      chinese: "这些画里，你最喜欢哪一张？理由也稍微告诉我一点吧。",
      file: "assets/audio/v20/voice/gallery-favorite.mp3",
      duration: 6.478367,
      expression: "neutral",
    },
    "praise-received": {
      id: "praise-received",
      scene: "被认真夸奖",
      japanese: "そんなところまで見てくれたんだ……。うん、嬉しい。",
      chinese: "原来你连那种小地方都注意到了……嗯，我很开心。",
      file: "assets/audio/v20/voice/praise-received.mp3",
      duration: 4.989388,
      expression: "neutral",
    },
    "wardrobe-compare": {
      id: "wardrobe-compare",
      scene: "衣橱比较",
      japanese: "並べてみると、雰囲気が違うね。今日は、どれがいいかな。",
      chinese: "放在一起看，感觉还真不一样呢。今天穿哪件好呢？",
      file: "assets/audio/v20/voice/wardrobe-compare.mp3",
      duration: 7.053061,
      expression: "neutral",
    },
    "outfit-home": {
      id: "outfit-home",
      scene: "粉色猫耳家居外套与奶油长裤",
      japanese: "このピンクの上着、袖が長くて落ち着くの。部屋では、これが楽。",
      chinese: "这件粉色外套袖子长长的，让人很安心。在房间里穿它很舒服。",
      file: "assets/audio/v20/voice/outfit-home.mp3",
      duration: 6.530612,
      expression: "neutral",
    },
    "outfit-artist": {
      id: "outfit-artist",
      scene: "蓝白格睡衣",
      japanese: "青いチェックのパジャマだよ。描くときも、ゆったりしてて好き。",
      chinese: "是蓝色格纹睡衣哦。画画时也很宽松，我很喜欢。",
      file: "assets/audio/v20/voice/outfit-artist.mp3",
      duration: 5.381224,
      expression: "neutral",
    },
    "outfit-outing": {
      id: "outfit-outing",
      scene: "薄荷针织外套与水手领裙装",
      japanese:
        "ミント色のカーディガン、似合ってる？　リボンも、曲がってないかな。",
      chinese: "薄荷色的针织外套，适合我吗？蝴蝶结也……没有歪吧。",
      file: "assets/audio/v20/voice/outfit-outing.mp3",
      duration: 6.635102,
      expression: "neutral",
    },
    "outfit-bedtime": {
      id: "outfit-bedtime",
      scene: "草莓奶油粉睡衣长裤",
      japanese: "いちごミルクみたいな色でしょ。このパジャマ、肌触りがいいの。",
      chinese: "像草莓牛奶一样的颜色吧。这套睡衣摸起来很舒服。",
      file: "assets/audio/v20/voice/outfit-bedtime.mp3",
      duration: 5.564082,
      expression: "neutral",
    },
    "outfit-hooded": {
      id: "outfit-hooded",
      scene: "薄荷灰猫耳连帽毯与长裤",
      japanese:
        "この毛布、猫の耳がついてるの。すっぽり包まると、あったかいよ。",
      chinese: "这条毯子带着猫耳朵。把自己整个裹起来，就暖暖的。",
      file: "assets/audio/v20/voice/outfit-hooded.mp3",
      duration: 7.079184,
      expression: "neutral",
    },
    "window-rain": {
      id: "window-rain",
      scene: "窗边细雨，仅在雨天触发",
      japanese: "細かい雨の音、聞こえる？　しばらく、ここで聞いていようか。",
      chinese: "听得见细细的雨声吗？要不要在这里听一会儿？",
      file: "assets/audio/v20/voice/window-rain.mp3",
      duration: 6.896327,
      expression: "neutral",
    },
    "bed-plush": {
      id: "bed-plush",
      scene: "床边抱玩偶",
      japanese:
        "この子、抱いてると落ち着くの。ふわふわで、ちょうどいい大きさ。",
      chinese: "抱着这个孩子就会安心。软软的，大小也刚刚好。",
      file: "assets/audio/v20/voice/bed-plush.mp3",
      duration: 6.4,
      expression: "sleepy",
    },
    goodnight: {
      id: "goodnight",
      scene: "晚安",
      japanese: "おやすみ。明日も……無理しないでね。",
      chinese: "晚安。明天也……不要勉强自己哦。",
      file: "assets/audio/v20/voice/goodnight.mp3",
      duration: 3.94449,
      expression: "sleepy",
    },
    "note-kept": {
      id: "note-kept",
      scene: "收好纸条",
      japanese: "その紙、なくさないでね。読んだら……そっとしまっておいて。",
      chinese: "那张纸不要弄丢哦。读完以后……轻轻收好吧。",
      file: "assets/audio/v20/voice/note-kept.mp3",
      duration: 6.19102,
      expression: "neutral",
    },
  },
};
CONTENT.outfits.home.name = "粉色猫耳家居服";
CONTENT.roomExperience.drawingBoard = {
  width: 1061,
  height: 1482,
  corners: [
    [528, 1100],
    [929, 1000],
    [1025, 1135],
    [635, 1240],
  ],
  small: "assets/v20/props/lap-drawing-board-720.webp",
  medium: "assets/v20/props/lap-drawing-board-1440.webp",
  image: "assets/v20/props/lap-drawing-board-4k.webp",
};
CONTENT.roomExperience.characterVoicePools = {
  room: ["welcome", "room-chair", "room-stay"],
  desk: ["desk-arrive", "drawing-one-line", "drawing-you-are-there"],
  wardrobe: ["wardrobe-compare", "outfit-current", "room-stay"],
  bed: ["bed-plush", "quiet-company", "drawing-you-are-there"],
  window: ["room-curtain", "quiet-company", "room-stay"],
};
CONTENT.outfits.home.description =
  "宽松的猫耳外套和柔软长裤，袖口里藏着一点点害羞。";
CONTENT.roomExperience.artworks = {
  door: {
    mint: {
      id: "door-mint",
      subject: "door",
      palette: "mint",
      title: "门缝看月亮的小猫",
      alt: "薄荷雨夜配色：浅银灰小猫从半开的门后探出圆脸和小爪，看向一弯月亮与两颗小星星",
      image: "assets/v20/drawings/door-mint-4k.webp",
      medium: "assets/v20/drawings/door-mint-1440.webp",
      small: "assets/v20/drawings/door-mint-720.webp",
      thumb: "assets/v20/drawings/door-mint-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    moon: {
      id: "door-moon",
      subject: "door",
      palette: "moon",
      title: "门缝看月亮的小猫",
      alt: "银蓝月光配色：浅银灰小猫从半开的门后探出圆脸和小爪，看向一弯月亮与两颗小星星",
      image: "assets/v20/drawings/door-moon-4k.webp",
      medium: "assets/v20/drawings/door-moon-1440.webp",
      small: "assets/v20/drawings/door-moon-720.webp",
      thumb: "assets/v20/drawings/door-moon-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    strawberry: {
      id: "door-strawberry",
      subject: "door",
      palette: "strawberry",
      title: "门缝看月亮的小猫",
      alt: "草莓黄昏配色：浅银灰小猫从半开的门后探出圆脸和小爪，看向一弯月亮与两颗小星星",
      image: "assets/v20/drawings/door-strawberry-4k.webp",
      medium: "assets/v20/drawings/door-strawberry-1440.webp",
      small: "assets/v20/drawings/door-strawberry-720.webp",
      thumb: "assets/v20/drawings/door-strawberry-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
  },
  blanket: {
    mint: {
      id: "blanket-mint",
      subject: "blanket",
      palette: "mint",
      title: "被窝里画星星的小猫",
      alt: "薄荷雨夜配色：浅银灰小猫藏在小被窝帐篷里，用短铅笔在白色画纸上认真画下一颗星星",
      image: "assets/v20/drawings/blanket-mint-4k.webp",
      medium: "assets/v20/drawings/blanket-mint-1440.webp",
      small: "assets/v20/drawings/blanket-mint-720.webp",
      thumb: "assets/v20/drawings/blanket-mint-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    moon: {
      id: "blanket-moon",
      subject: "blanket",
      palette: "moon",
      title: "被窝里画星星的小猫",
      alt: "银蓝月光配色：浅银灰小猫藏在小被窝帐篷里，用短铅笔在白色画纸上认真画下一颗星星",
      image: "assets/v20/drawings/blanket-moon-4k.webp",
      medium: "assets/v20/drawings/blanket-moon-1440.webp",
      small: "assets/v20/drawings/blanket-moon-720.webp",
      thumb: "assets/v20/drawings/blanket-moon-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    strawberry: {
      id: "blanket-strawberry",
      subject: "blanket",
      palette: "strawberry",
      title: "被窝里画星星的小猫",
      alt: "草莓黄昏配色：浅银灰小猫藏在小被窝帐篷里，用短铅笔在白色画纸上认真画下一颗星星",
      image: "assets/v20/drawings/blanket-strawberry-4k.webp",
      medium: "assets/v20/drawings/blanket-strawberry-1440.webp",
      small: "assets/v20/drawings/blanket-strawberry-720.webp",
      thumb: "assets/v20/drawings/blanket-strawberry-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
  },
  pencil: {
    mint: {
      id: "pencil-mint",
      subject: "pencil",
      palette: "mint",
      title: "抱着大铅笔的小猫",
      alt: "薄荷雨夜配色：圆脸短四肢的浅银灰小猫坐着抱住一支大铅笔，身边散着三颗小星星",
      image: "assets/v20/drawings/pencil-mint-4k.webp",
      medium: "assets/v20/drawings/pencil-mint-1440.webp",
      small: "assets/v20/drawings/pencil-mint-720.webp",
      thumb: "assets/v20/drawings/pencil-mint-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    moon: {
      id: "pencil-moon",
      subject: "pencil",
      palette: "moon",
      title: "抱着大铅笔的小猫",
      alt: "银蓝月光配色：圆脸短四肢的浅银灰小猫坐着抱住一支大铅笔，身边散着三颗小星星",
      image: "assets/v20/drawings/pencil-moon-4k.webp",
      medium: "assets/v20/drawings/pencil-moon-1440.webp",
      small: "assets/v20/drawings/pencil-moon-720.webp",
      thumb: "assets/v20/drawings/pencil-moon-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
    strawberry: {
      id: "pencil-strawberry",
      subject: "pencil",
      palette: "strawberry",
      title: "抱着大铅笔的小猫",
      alt: "草莓黄昏配色：圆脸短四肢的浅银灰小猫坐着抱住一支大铅笔，身边散着三颗小星星",
      image: "assets/v20/drawings/pencil-strawberry-4k.webp",
      medium: "assets/v20/drawings/pencil-strawberry-1440.webp",
      small: "assets/v20/drawings/pencil-strawberry-720.webp",
      thumb: "assets/v20/drawings/pencil-strawberry-480.webp",
      width: 3840,
      height: 2880,
      mediumWidth: 1440,
      smallWidth: 720,
    },
  },
};
CONTENT.roomExperience.drawingBoard = {
  width: 1061,
  height: 1482,
  corners: [
    [528, 1100],
    [929, 1000],
    [1025, 1135],
    [635, 1240],
  ],
  small: "assets/v20/props/lap-drawing-board-720.webp",
  medium: "assets/v20/props/lap-drawing-board-1440.webp",
  image: "assets/v20/props/lap-drawing-board-4k.webp",
};

CONTENT.roomExperience.windowGlass = {
  width: 1440,
  height: 802,
  polygons: [
    [
      [1110, 8],
      [1177, 8],
      [1177, 77],
      [1110, 85],
    ],
    [
      [1207, 8],
      [1295, 8],
      [1295, 63],
      [1207, 72],
    ],
    [
      [1110, 112],
      [1177, 105],
      [1177, 211],
      [1110, 218],
    ],
    [
      [1207, 103],
      [1295, 93],
      [1295, 150],
      [1207, 161],
    ],
  ],
};
